version: '3.8'
services:

  exercise-service:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on: 
      database: 
        condition: service_healthy  

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q" ]
      interval: 5s
      timeout: 2s
      retries: 10  

  data-initializer:
    build: 
      context: .
      dockerfile: Dockerfile.insertion
    command: "sh -c 'npx prisma migrate deploy && node dataInsertion.js'"
    depends_on:
      database: 
        condition: service_healthy     
